spring:
  application:
    name: biblia
  datasource:
    url: jdbc:postgresql://localhost:5432/biblia
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
